language: objective-c
os: osx
osx_image: xcode8.3
branches:
  only:
    - master

  global:
    secure: gZMOaHQIeG7nplBCuH7EKf9o6Ez2rtoSskrv3nOTziSxFfZq322MrxvkidDpEN7AKWYQm27FO+tCzgq0slXb578lQ9P5ySDwEdExKtk/jMtKsBsf3cr4dzSMiqV5D5TbsH2jE9HQlpYUoJeoMBicR2XsTmd7wiu2jAzNBFqGfiY=

matrix:
  include:
  - osx_image: xcode8.3
    env:
      - SIMULATOR_NAME='iPhone 6 (10.3)'
      - TEST_TYPE=installation_manual
      - TEST_TYPE=installation_carthage
      - TEST_TYPE=installation_cocoapods
      - TEST_TYPE=installation_cocoapods_frameworks
      - TEST_TYPE=lint
      - TEST_TYPE=tests
      - TEST_TYPE=analyzer
      - TEST_TYPE=documentation
  - osx_image: xcode9
    env:
      - SIMULATOR_NAME='iPhone 6 (10.3)'
      - TEST_TYPE=installation_manual
      - TEST_TYPE=installation_carthage
      - TEST_TYPE=installation_cocoapods
      - TEST_TYPE=installation_cocoapods_frameworks
      - TEST_TYPE=tests
  - osx_image: xcode9
    env:
      - SIMULATOR_NAME='iPhone 6 (11.0)'
      - TEST_TYPE=installation_manual
      - TEST_TYPE=installation_carthage
      - TEST_TYPE=installation_cocoapods
      - TEST_TYPE=installation_cocoapods_frameworks
      - TEST_TYPE=lint
      - TEST_TYPE=tests
      - TEST_TYPE=analyzer
      - TEST_TYPE=documentation

before_install:
- SIMULATOR_ID=$(xcrun instruments -s | grep -o $SIMULATOR_NAME \[.*\]" | grep -o
  "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
script:
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
- "./ci_scripts/check_version.rb"
- "./ci_scripts/check_public_headers.rb"
- "./ci_scripts/check_category_linking.rb"
- "./ci_scripts/check_resource_bundle.rb"
- '[ "$TEST_TYPE" != lint ] || ./ci_scripts/check_fauxpas.sh'
- '[ "$TEST_TYPE" != tests ] || travis_retry ./ci_scripts/run_tests.sh "$SIMULATOR_ID"'
- '[ "$TEST_TYPE" != analyzer ] || ./ci_scripts/run_analyzer.sh'
- '[ "$TEST_TYPE" != installation_cocoapods ] || ./Tests/installation_tests/cocoapods/without_frameworks/test.sh "$SIMULATOR_ID"'
- '[ "$TEST_TYPE" != installation_cocoapods_frameworks ] || ./Tests/installation_tests/cocoapods/with_frameworks/test.sh "$SIMULATOR_ID"'
- '[ "$TEST_TYPE" != installation_manual ] || travis_retry ./Tests/installation_tests/manual_installation/test.sh "$SIMULATOR_ID"'
- '[ "$TEST_TYPE" != installation_carthage ] || ./Tests/installation_tests/carthage/test.sh "$SIMULATOR_ID"'
- '[ "$TEST_TYPE" != documentation ] || ./ci_scripts/check_documentation.sh'
